@host = http://localhost:5256

POST {{host}}/login/
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "1234",
  "deviceToken": "tOq0z2Eo8Qlg3y8JNxd1i0KZdhK8TkQVmlPuDnP8fhc="
}

###
